### ISSUE TITLE
Log object and log shortcuts

### ISSUE THREAD

**Issue by AdrienGiboire** [IonicaBizau/cute-logger#13]
Hey!
- I'd like to know if it's on purpose it's impossible to _natively_ log objects?
- I'd like to know if it would make sense to _encapsulate_ things like `Debug.log("Something to log", "info")` writing `Debug.info("Something to log")`?

I've forked the project to extend it for personal uses. If it makes sense, I'd prefer to contribute accordingly instead :)

**Comment by IonicaBizau** [comment]
@AdrienGiboire There's a similar issue: #5. Maybe let's do it—basically just creating few aliases.

PR welcome! 👍

**Comment by IonicaBizau** [comment]
This was fixed in #18. Thanks :grin:
